kn.rb
We are a mixed team of Mac/Linux users, therefor Linux support would be quite helpful for us. :)
=> Add linux support.

kn.rb, kn@0.17.rb, kn@0.18.rb
=> Update to 0.19.0

kn.rb, kn@0.17.rb, kn@0.18.rb
=> Update version to latest releases

kn@0.19.rb
- Update for v0.20.0 and v0.19.1
=> homebrew knative client release v0.20.0

kn@0.19.rb
=> Fix kn@0.19 formula

kn@0.20.rb
- update for v0.21.0 and v0.20.0
/assign @dsimansk @rhuss
=> homebrew knative client release v0.21.0

kn.rb, kn@0.17.rb, kn@0.18.rb, kn@0.19.rb, kn@0.20.rb
=> Fix update/upgrade warnings due to fileutils import

kn@0.21.rb
=> homebrew knative client release v0.22.0

kn@0.22.rb
- :gift: Release v0.23
-
-
/kind <kind>
Fixes #
**Release Note**
```release-note
```
**Docs**
```docs
```
=> release v0.23

kn@0.26.rb
- :gift: Update client to v1.0.0
/cc @rhuss @maximilien
=> Update client to v1.0.0

OWNERS
Use same aliases as per `knative/client` repository.
PTAL
/cc @rhuss @navidshaikh @maximilien
=> Fix owners file to reference aliases

kn@1.1.rb
Part of release train for v1.2
/assign @rhuss @dsimansk
=> Update client to v1.2.0

kn@1.3.rb
update kn to v1.4.0
/cc @rhuss @ikvmw 
**Release Note**
```release-note
update kn to v1.4.0
```
=> update kn to v1.4.0

kn@1.4.rb
=> Update kn client to 1.5

kn@1.5.rb
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
=> Update current version to 1.6

kn@1.6.rb
=> Update formula to release v1.7.0

hack/update-versions.sh, kn.rb, kn@1.6.rb
Fixes: https://github.com/knative/homebrew-client/issues/51
- Added logic to detect arm64, borrowed ideas from Hashicorp's tap repo. https://github.com/hashicorp/homebrew-tap/blob/master/Formula/terraform.rb
/kind enhancement
Fixes #
**Release Note**
```release-note
```
**Docs**
```docs
```
/cc @knative/knative-release-leads @knative/client-writers
=> Install arm builds via brew

kn@1.6.rb, kn@1.7.rb
Generated by:
```
CURRENT_RELEASE=1.8.0 PREVIOUS_RELEASE=1.7.0 ./hack/update-versions.sh
```
- Update kn to release v1.8.0
/cc @nak3 @lionelvillard @upodroid @rhuss
=> Update kn to release v1.8.0

kn@1.8.rb
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
/assign @rhuss @dsimansk @evankanderson
=> Update client for release v1.9

kn@1.9.rb
- Update kn to v1.10.0
/cc @knative/knative-release-leads @rhuss
=> Update kn to v1.10.0

kn@1.10.rb
- Update kn to v1.11.0
/cc @knative/knative-release-leads 
/cc @rhuss
=> Update kn to v1.11.0

kn@1.11.rb
- :gift: Update kn to v1.12 release
Generated by:
```
CURRENT_RELEASE=1.12.0 PREVIOUS_RELEASE=1.11.0 ./hack/update-versions.sh
```
/cc @knative/knative-release-leads
=> Update kn to v1.12 release

.github/workflows/knative-homebrew-test.yaml, hack/verify-taps.sh, kn@1.6.rb
Per title, same as plugins homebrew tap. 
/cc @rhuss
=> Add script and GH action to verify tap
